### ISSUE TITLE
Key combinations needs to be changed

### ISSUE THREAD

**Issue by rrkishoreraj** [kgashok/promises-book-examples#6]
Sir, a slight change needs to be done in the description ( within the **parentheses**) that is next to the **submit** button. It's been given as **_ctrl-alt-i_** instead of **_ctrl-shift-i_**, sir.

![image](https://user-images.githubusercontent.com/29670674/51245321-5190ee00-19ad-11e9-8579-d32638f16ec8.png)

**Comment by kgashok** [comment]
Good catch, @rrkishoreraj - has been fixed.
